[package]
name = "starry_mosaic"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
float-cmp = "0.9.0"
image = "0.24.2"
palette = "0.6.0"
voronoice = "0.2.0"

[features]
mosaic_with_preset_coloring = []
