name: Continuous integration

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check library
      run: cargo check
    - name: Build library in release mode
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
